use jalainternship;

select snum,sname,city,comm from salespeople;
select distinct snum from orders;
select sname,comm from salespeople;
select * from customers where rating > 100;
select orderno,amount,order_date from orders;
select * from customers where city='San Jose' and rating >=200;
select * from customers where city='San Jose' or rating >200;
select * from orders where amount>1000;
select sname,city from salespeople where city='London' 
and comm > 1000;
select cname from customers where rating <=100 or city='Rome';
select * from salespeople where city in ('Barcelona', 'London');
select * from salespeople where comm >10000 and comm <12000;
select * from customers where city is null;
select * from orders where order_date in ('2021-02-01','2021-03-21');
select * from customers where sname='MSD';
select * from customers where cname like 'A%' or cname like 'B%';
select orderno from orders where amount != 0 or amount is not null;
select count(distinct snum) from orders;
select snum,order_date,max(amount) from orders group by order_date ,snum  order by order_date,snum;
select order_date,snum,amount from orders where amount>3000;
select order_date from orders where amount = (select max(amount) from orders);
select count(*) from orders where order_date > '2021-03-01';
select count(distinct city) from customers;
select c.cname,min(o.amount) from customers c,orders o group by c.cname;
select min(cname) from customers where cname like 'T%';
select 'For ',char(order_date,'dd/mm/yy'),' there are ',count(*),' Orders' from orders group by order_date;
select o.orderno,o.snum,s.comm from orders o join salespeople s
where o.snum=s.snum order by o.orderno asc; 
select 'For the city (',city,'), the highest rating is : (',max(rating),')' from customers group by city;
select order_date,count(orderno) from orders group by order_date order by count(order_date);
select c.cname,s.sname,c.city from customers c join salespeople s where c.city=s.city;
select c.cname,s.sname from customers c join salespeople s where c.sname=s.sname;
select customers.cname,orders.orderno from customers,salespeople,orders where orders.snum=salespeople.snum and customers.sname=salespeople.sname;
select orders.orderno,salespeople.sname,customers.cname from orders,customers,salespeople where orders.snum=salespeople.snum and customers.sname=salespeople.sname;
select c.cname,s.sname from salespeople s join customers c where s.comm>12000 and s.sname = c.sname;
select s.comm,s.sname from salespeople s join customers c where c.rating > 100 and s.sname=c.sname;
select x.cname,y.cname from customers x, customers y where x.rating=y.rating and x.cname!=y.cname;
select cname,sname from customers c where sname='MSD' order by cname; 
select cname from customers where city = ( select customers.city  from customers, salespeople where customers.sname = salespeople.sname and salespeople.sname = 'Hussey');
select cname,city from customers where rating=(select rating from customers where cname='Good');
select orderno from orders where snum=(select snum from salespeople where sname='Peter');
select *  from orders where amount > ( select avg(amount)  from orders where order_date = '2021-03-21');
select avg(comm) from salespeople where city = 'London';
select orderno from orders where snum in (select snum from salespeople where city='Chennai');
select comm from salespeople where sname in (select sname from customers where city='Chennai');
Select cname, rating from customers where rating > ( select avg(rating)  from customers where city = 'San Jose'); 
